# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
# startup tasks
tasks:
  - init: ./mvnw package -DskipTests
    command: java -jar target/*.jar

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview
