scrolls:
    #Scroll cooldown time
    time: 180
    #Scroll teleport delay (set to 0 to have no tp)
    tpdelay: 5
    #Teleport Delay message
    tpdelaymsg: "&aYou have begun to teleport... Do not move for %seconds% seconds"
    #Scroll name (Reusable Scrolls)
    scrollName: "&aReusable Teleportation Scroll"
    #Scroll name (Non-Reusable)
    cheapScrollName: "&aCheap Teleportation Scroll"
    #Max Entities Around
    #This prevents scrolls from being dropped if there are more than
    #- 'maxEntities' entities in a radius (maxEntitiesRadius) of the killed entity
    maxEntities: 15
    #The radius in which the plugin checks for mobs centered on the location of the killed entity
    maxEntitiesRadius: 16
    
    #Allow Scroll drops from spawners
    allowSpawners: false
    
    #Drop chances
    
    #Mob Drops defines what mobs can drop Scrolls
    #You can add to the list as you see fit
    mobDrops:
        - 'SKELETON'
        - 'ZOMBIE'
        - 'SPIDER'
    #Allow the chance for both scrolls to be dropped from one entity death
    doubleDrops: false
    #Drop chances for each scroll (1 being 100%, 0 being 0%)
    cheapScrollDrop: 0.05
    scrollDrop: 0.02
orbs:
    #Displayname changes the enchanted item's name
    #Use '%currentname%' to use the item's current name in lore
    displayName: '&cCorrupted %currentname%'

    #Chance table
    itemUpgradeChance: 0.2
    enchantmentUpgradeChance: 0.4
    failChance: 0.2
    downgradeChance: 0.2

    #Enchantment Level Table
    #First Number (Ex: 3,2,1,-1) is the level added to the randomly selected enchantment.
    #Second number is the chance that level modifier has of being used.
    etable:
        3: 0.1
        2: 0.15
        1: 0.5
        -1: 0.25
    
    #Orb Dropping
    dropChance: 0.5
    spawnerDrops: false
    
    #Only players with "orbs.drops" can make mobs drop orbs
    usePermission: true

    #Allow items with already existing lore? (Likely modified by a previous plugin)
    allowLoreItems: false

    #Vaal Orb display name
    orbDisplayName: "&9Vaal Orb"
    
    modifiedmessage: 
        - "&8This item has been corrupted."
        - "&8You can no longer modify it."
    #Vaal Orb lore
    orbLore:
        - '&6A strange orb.'
        - '&8Im not good with lores'
    #Blocked enchantments
    blockedenchants:
        - 'Looting'
        - 'Fortune'
        - 'Mending'
        - 'Silk_Touch'
    